language: python

python:
  - "3.6"

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

env:
  global:
    - PGPORT=5432
    - PGHOST=localhost
    - PGDATABASE=fhirbase
    - PGUSER=postgres

install:
  # Install fhirbase
  - mkdir bin
  - export PATH=$PATH:$PWD/bin
  - curl -L https://github.com/fhirbase/fhirbase-core/releases/download/nightly-build/fhirbase-linix-amd64 > bin/fhirbase
  - chmod +x bin/fhirbase
  # Install requirements
  - pip install tox tox-travis

before_script:
  # Use default port
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/10/main/postgresql.conf
  # Use 9.6 auth config:
  - sudo cp /etc/postgresql/{9.6,10}/main/pg_hba.conf
  - sudo service postgresql restart
  # Prepare db
  - psql -c 'create database fhirbase;' -d postgres -U postgres
  - bin/fhirbase init 3.0.1
  - psql -c '\dt'
  - psql -c '\dt' -d fhirbase
  - psql -c '\dt' -d postgres
  - psql -c '\df'
  - psql -c '\df' -d fhirbase
  - psql -c '\df' -d postgres


script:
  - tox

after_success:
  - pip install codecov
  - codecov -e TOXENV

notifications:
  email: false
