version: '3'

services:
  wait_for:
    image: jwilder/dockerize
    command: |
      dockerize
       -wait tcp://db:5432
       -timeout 60s
    networks:
      - fhirbase

  tests:
    build: .
    command: pytest --doctest-modules --cov-config=.coveragerc --cov fhirbase
    volumes:
      - ./shared:/app/user/shared
    depends_on:
    - db
    networks:
    - fhirbase
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGPORT: 5432
      PGHOST: db
      PGDATABASE: postgres
