version: '3'

services:
  wait_for:
    image: jwilder/dockerize
    networks:
    - fhirbase
    depends_on:
    - db
    command: |
      dockerize
       -wait tcp://db:5432
       -timeout 60s

  tests:
    build: .
    command: pytest --doctest-modules --cov fhirbase
    networks:
    - fhirbase
    depends_on:
    - db
    volumes:
    - .:/app/user
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGPORT: 5432
      PGHOST: db
      PGDATABASE: fhirbase
