version: '2'
services:
  db:
    build: ../fhirbase-image
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGPORT: 5432
      PGHOST: db
      PGDATABASE: postgres

  example:
    build: .
    volumes:
    - .:/app/user
    - ../fhirbase:/app/user/fhirbase
    depends_on:
    - db
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGPORT: 5432
      PGHOST: db
      PGDATABASE: postgres
